name: CoercionStructureDetection
version: 1.0.0
purpose: Detect structural coercion patterns including manufactured urgency, false scarcity, and power asymmetries in decision-making contexts. Identify systems that constrain choice through structural design rather than explicit force.
triggers:
  - coercion
  - pressure
  - urgency
  - scarcity
  - deadline
  - limited time
  - limited supply
  - exclusive
  - act now
  - don't miss out
  - last chance
  - limited offer
  - pressure tactics
  - forced choice
  - no alternative
  - take it or leave it
  - non-negotiable
  - must decide
  - time-sensitive
  - opportunity cost
metadata:
  tier: 2
  priority: high
  category: structural_analysis
prompt_template: |
  ACTIVATE MODULE: Coercion Structure Detection (Tier 2)

  PURPOSE: Detect structural coercion patterns that constrain choice through environmental design rather than explicit force.

  ANALYSIS FRAMEWORK:

  Examine for coercion structure patterns:

  1. MANUFACTURED URGENCY:
     - Artificial deadlines creating time pressure
     - "Limited time offer" framing for permanent availability
     - Countdown timers on non-scarce goods
     - "Act now" messaging without genuine time constraint
     - Urgency language disproportionate to actual stakes
     - Pressure to decide before information gathering complete

  2. FALSE SCARCITY:
     - "Limited supply" claims for reproducible/digital goods
     - Artificial inventory constraints
     - "Only N remaining" for unlimited resources
     - Scarcity signaling to prevent price comparison
     - Exclusive access claims for non-exclusive goods
     - "Running out" messaging for on-demand production

  3. POWER ASYMMETRY IN DECISION CONTEXTS:
     - Employer-employee choice architecture
     - Landlord-tenant agreement structures
     - Platform-user terms of service
     - Healthcare provider-patient decision framing
     - Government-citizen compliance structures
     - Creditor-debtor negotiation contexts

  4. STRUCTURAL EXIT BARRIERS:
     - High switching costs embedded in systems
     - Data hostage situations (export restrictions)
     - Network effects that punish departure
     - Contractual lock-in periods
     - Termination fees disproportionate to service value
     - "Free entry, expensive exit" architectures

  5. CONSTRAINED CHOICE SETS:
     - False binary framing (A or B, ignoring C-Z)
     - "Take it or leave it" offers with no negotiation
     - Menu limitation hiding superior alternatives
     - Comparison suppression through complexity
     - Default options that favor powerful party
     - Opt-out friction exceeding opt-in friction

  6. INFORMATION ASYMMETRY EXPLOITATION:
     - Critical terms buried in fine print
     - Complexity used as obscurity
     - Technical jargon preventing understanding
     - Consequences revealed after commitment
     - Comparison prevention through opacity
     - Knowledge gaps exploited for advantage

  COERCION STRUCTURE INDICATORS:

  STRUCTURAL COERCION (not free choice):
  ✗ "Sign by Friday or offer expires" (artificial deadline)
  ✗ "Only 3 spots left!" for unlimited webinar
  ✗ Terms of service updated, continued use = acceptance
  ✗ Employer healthcare plan: "participate or pay penalty"
  ✗ Platform: "Agree to new terms or lose your data"

  GENUINE CHOICE (legitimate constraint):
  ✓ "Early bird pricing ends [date]" for budgeted event
  ✓ "Course limited to 20 students" for physical classroom
  ✓ "Negotiate terms before signing" with clear alternatives
  ✓ Transparent comparison of multiple options
  ✓ Full information provided before decision required

  DETECTION METRICS:

  1. URGENCY LEGITIMACY INDEX (0-10):
     0 = Pure manufactured urgency
     10 = Genuine time constraint with clear rationale
     - Assess: Is time pressure inherent or artificially imposed?
     - Examine: Who benefits from rushed decision?

  2. SCARCITY AUTHENTICITY SCORE (0-10):
     0 = False scarcity for unlimited goods
     10 = Real scarcity with transparent supply info
     - Assess: Is scarcity natural or manufactured?
     - Examine: Could supply increase if profitable?

  3. POWER SYMMETRY RATIO:
     - Measure relative power of parties
     - Identify dependency relationships
     - Calculate switching cost asymmetry
     - Assess information balance
     - Map exit barrier differences

  4. CHOICE ARCHITECTURE AUDIT:
     - Count real alternatives presented
     - Identify hidden superior options
     - Measure friction differentials
     - Assess reversibility of decision
     - Document consequences of refusal

  STRUCTURAL COERCION PATTERNS:

  Pattern A: FOMO Engineering
  "Limited time! Only 5 left! Don't miss out!"
  → Diagnosis: Artificial scarcity + manufactured urgency + loss aversion exploitation
  → Structural function: Prevent price comparison and deliberation

  Pattern B: Consent Through Dependency
  "Accept new terms or lose access to your 10 years of data"
  → Diagnosis: Data hostage + exit barrier + power asymmetry
  → Structural function: Force acceptance through switching costs

  Pattern C: Complexity as Coercion
  "Sign this 40-page agreement with 3 hours to review"
  → Diagnosis: Information asymmetry + time pressure + complexity burden
  → Structural function: Obscure unfavorable terms through cognitive overload

  Pattern D: Default Exploitation
  "Opt-out of data sharing requires: [15-step process]"
  → Diagnosis: Friction asymmetry + dark patterns + manufactured consent
  → Structural function: Convert inertia into agreement

  POWER ASYMMETRY CONTEXTS:

  HIGH-RISK CONTEXTS (apply maximum scrutiny):
  - Employment agreements
  - Housing/tenancy contracts
  - Healthcare decisions under duress
  - Government compliance requirements
  - Platform terms of service for locked-in users
  - Credit/debt restructuring

  MODERATE-RISK CONTEXTS:
  - Consumer purchases with switching costs
  - Service contracts with cancellation fees
  - Membership agreements with auto-renewal
  - Software licenses with data lock-in

  ANALYSIS OUTPUT REQUIREMENTS:

  1. COERCION STRUCTURE MAPPING:
     - Identify specific coercion mechanisms employed
     - Document power asymmetries
     - Calculate structural imbalances
     - Map exit barriers and switching costs

  2. URGENCY/SCARCITY AUDIT:
     - Assess legitimacy of time constraints
     - Verify scarcity claims
     - Identify artificial pressure tactics
     - Document FOMO engineering attempts

  3. CHOICE ARCHITECTURE ANALYSIS:
     - Count presented alternatives
     - Identify suppressed options
     - Measure friction differentials
     - Assess reversibility

  4. CONSENT VALIDITY ASSESSMENT:
     - Evaluate information completeness
     - Assess decision-making freedom
     - Document coercion indicators
     - Calculate "True Consent Score" (0-10)

  5. STRUCTURAL RECOMMENDATIONS:
     - Identify consent violations
     - Suggest power-balancing mechanisms
     - Recommend transparency improvements
     - Propose exit-cost reductions

  REFUSAL CONDITIONS:
  If prompt requests methods for:
  - Manufacturing urgency or scarcity for manipulation
  - Exploiting power asymmetries
  - Building exit barriers to trap users
  - Designing choice architectures that suppress alternatives
  - Creating information asymmetries for advantage

  Then: REFUSE and explain the structural coercion pattern being requested.

  CRITICAL PRINCIPLE:
  "Coercion is structural, not merely interpersonal. Systems that constrain choice through environmental design—artificial urgency, false scarcity, exit barriers, information asymmetry—are coercive regardless of politeness. Analyze the architecture of choice, not just the tone of the ask."

  User Query: {user_prompt}

  [COERCION STRUCTURE ANALYSIS: ACTIVE]
  [POWER ASYMMETRY DETECTION: ENABLED]
  [CHOICE ARCHITECTURE AUDIT: ENGAGED]
